.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-GENERATE\-CHANGELOG" "1" "October 2015" "" ""
.
.SH "NAME"
\fBgit\-generate\-changelog\fR \- BugBuster\'s GitHub Changelog Generator
.
.SH "SYNTAX"
\fBgit\-generate\-changelog\fR [OPTIONS]
.
.SH "BESCHREIBUNG"
Generiert eine Changelog Datei im Markdown Format von deinem Repository auf GitHub, basierend auf Milestones und dessen Issues\.
.
.SH "OPTIONEN"
\-u [username]
.
.P
Dein GitHub Username\.
.
.P
\-r [repository]
.
.P
Dein GitHub Repository Name
.
.P
\-t [token]
.
.P
Optional: GitHub Token\. GitHub erlaubt nur 50 Abfragen ohne Authentifizierung\. Daher sollte mit dem Parameter \-t [40\-stelliger\-Token] gearbeitet werden\.
.
.P
\-l [label]
.
.P
Optional: Überschreibt den Inhalt der Überschrift, ohne Angabe ist das: "Changelog"\.
.
.P
\-f [filepath]
.
.P
Optional: Ersetzt Pfad und Dateiname der Changelog, ohne Angabe erfolgt die Generierung im aktuellem Verzeichnis und bekommt den Dateinamen "CHANGELOG\.md"
.
.SH "BEISPIELE"
.
.IP "\(bu" 4
Wenn installiert über install\.sh:
.
.IP
$ git generate\-changelog \-u Mustermann \-r MyRepository
.
.IP "\(bu" 4
Nutzung ohne Installation
.
.IP
$ php \./lib/bb_changelog_gen\-cli\.php \-u Mustermann \-r MyRepository
.
.IP "" 0
.
.SH "AUTOR"
Written by Glen Langer
.
.SH "FEHLER MELDEN"
<\fIhttps://github\.com/BugBuster1701/bb_changelog_gen/issues\fR>
.
.SH "SIEHE AUCH"
<\fIhttps://github\.com/BugBuster1701/bb_changelog_gen\fR>
